version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@3.0.0

jobs:
  install_and_test:
    machine: true
    steps:
      - run: npm install --save
      - run: npm test
      - run: npm start

workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - install_and_test
     
