version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@3.0.0

jobs:
  run_tests:
     steps:
       - checkout
       - run:
         name: Install npm dependencies
         command: |
            npm install --save
      - run:
        name: run tests
        commad: |
          ./node_modules/.bin/mocha
workflows:
  build-tests:
    jobs:
      - run_tests
