version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  run_tests:
     - image: circleci/node@3.0.0
     steps:
       - checkout
       - run:
         name: Install npm dependencies
         command: |
            npm install --save
      - run:
        name: run tests
        commad: ./node_modules/.bin/mocha
workflows:
  build-tests:
    jobs:
      - run_tests
