version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@3.0.0

jobs:
  test:
    machine: true
    steps:
      - run: npm test
  deploy:
    machine: true
    steps:
      - run: npm start

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
